#!/bin/zsh

set -e
if [ ! -f "$3/Library/MariaDB/ServiceData/mysql/user.frm" ]; then
    unset TMPDIR

    "$3/Library/MariaDB/Prefix/scripts/mysql_install_db" --verbose --user=daemon \
        --basedir="$3/Library/MariaDB/Prefix" --datadir="$3/Library/MariaDB/ServiceData" \
        --tmpdir="$3/tmp"
fi

mkdir -p $3/Library/Logs/MariaDB
touch $3/Library/Logs/MariaDB/stdout.log $3/Library/Logs/MariaDB/stderr.log
chown daemon:wheel $3/Library/Logs/MariaDB/stdout.log $3/Library/Logs/MariaDB/stderr.log
