#!/bin/zsh

set -e

if [ "$1" = "start" ]; then
    if [ $UID -ne 0 ]; then
        echo "mariadbctl $1 must be run as root." 1>&2
        exit 1
    fi

    launchctl load /Library/LaunchDaemons/me.sunsol.mariadb.plist
elif [ "$1" = "stop" ]; then
    if [ $UID -ne 0 ]; then
        echo "mariadbctl $1 must be run as root." 1>&2
        exit 1
    fi

    launchctl unload /Library/LaunchDaemons/me.sunsol.mariadb.plist
elif [ "$1" = "restart" ]; then
    if [ $UID -ne 0 ]; then
        echo "mariadbctl $1 must be run as root." 1>&2
        exit 1
    fi

    launchctl unload /Library/LaunchDaemons/me.sunsol.mariadb.plist || :
    launchctl load /Library/LaunchDaemons/me.sunsol.mariadb.plist
elif [ "$1" = "status" ]; then
    launchctl print system/me.sunsol.mariadb
else
    echo 'usage: mariadbctl <arg>' 1>&2
    echo '<arg> can be one of start/stop/restart/status' 1>&2
    exit 1
fi
