#!/bin/zsh

set -e

if [ $UID -ne 0 ]; then
    echo 'mariadb_ctl must be run as root.' 1>&2
    exit 1
fi

if [ "$1" = "start" ]; then
    launchctl load /Library/LaunchDaemons/me.sunsol.mariadb.plist
elif [ "$1" = "stop" ]; then
    launchctl unload /Library/LaunchDaemons/me.sunsol.mariadb.plist
elif [ "$1" = "restart" ]; then
    launchctl unload /Library/LaunchDaemons/me.sunsol.mariadb.plist || :
    launchctl load /Library/LaunchDaemons/me.sunsol.mariadb.
elif [ "$1" = "status" ]; then
    launchctl print system/me.sunsol.mariadb
else
    echo 'usage: mariadb_ctl <arg>' 1>&2
    echo '<arg> can be one of start/stop/restart/status' 1>&2
    exit 1
fi
